Add regression test for issue 85
    error[E0507]: cannot move out of a shared reference
       --> tests/test_expr.rs:269:5
        |
    269 |     clone!(&A).consume_self();
        |     ^^^^^^^^^^^--------------
        |     |          |
        |     |          value moved due to this method call
        |     move occurs because value has type `A`, which does not implement the `Copy` trait
        |
    note: this function takes ownership of the receiver `self`, which moves value
       --> tests/test_expr.rs:266:25
        |
    266 |         fn consume_self(self) {}
        |                         ^^^^