Add regression test for issue 91
Currently fails with:

    error: `"1_u32"` is not a valid identifier
      --> tests/test_expr.rs:56:49
       |
    56 |                         [<vec_ $bit>].insert(0, [<1_u $bit>]);
       |                                                 ^^^^^^^^^^^^
    ...
    63 |     vec_insert!(32);
       |     --------------- in this macro invocation
       |
       = note: this error originates in the macro `vec_insert` (in Nightly builds, run with -Z macro-backtrace for more info)

    error[E0425]: cannot find function `vector_insert_32_bit` in this scope
      --> tests/test_expr.rs:64:5
       |
    64 |     vector_insert_32_bit(2);
       |     ^^^^^^^^^^^^^^^^^^^^ not found in this scope