Add regression test for issue 70
Compilation currently fails with:

    error: expected identifier after `:`
      --> tests/test_attr.rs:56:21
       |
    56 |         m!(#[x = foo::Bar])
       |                     ^^