Avoid unused_self clippy pedantic lint in test
    error: unused `self` argument
       --> tests/test_expr.rs:266:25
        |
    266 |         fn consume_self(self) {}
        |                         ^^^^
        |
        = note: `-D clippy::unused-self` implied by `-D clippy::pedantic`
        = help: consider refactoring to a associated function
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_self